# Generated by Django 5.1.1 on 2024-10-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Имя автора"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Фамилия автора"),
                ),
            ],
            options={
                "verbose_name": "фамилия",
                "verbose_name_plural": "фамилии",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите наименование",
                        max_length=100,
                        null=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "blog_content",
                    models.TextField(blank=True, null=True, verbose_name="Содержимое"),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату создания",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Признак публикации",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog",
                        related_query_name="blogs",
                        to="blogs.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["blog_name", "blog_content", "is_published", "author"],
            },
        ),
    ]
