# Generated by Django 5.1.1 on 2024-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_blog_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="views_count",
        ),
        migrations.AddField(
            model_name="blog",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
