# Generated by Django 5.1.1 on 2024-10-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_rename_view_counter_blog_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Автоматически генерируется из заголовка",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
