# Generated by Django 5.1.1 on 2024-09-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "category_description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Введите наименование товара",
                        max_length=100,
                        null=True,
                        verbose_name="Наименование товара",
                    ),
                ),
                (
                    "product_description",
                    models.TextField(null=True, verbose_name="Описание товара"),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото товара",
                        null=True,
                        upload_to="catalog/images",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Введите цену товара",
                        max_digits=10,
                        null=True,
                        verbose_name="Цена товара",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Укажите дату создания",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        related_query_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": [
                    "product_name",
                    "product_description",
                    "product_price",
                    "category",
                    "created_at",
                    "updated_at",
                ],
            },
        ),
    ]
